name: "dbt_project"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_project"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Seeds configuration
seeds:
  dbt_project:
    +quote_columns: false

    # MongoDB CSVs - configure data types
    mongodb:
      +schema: seeds

      medicaldb.users:
        +column_types:
          _id: varchar(50)
          updateSequence: bigint
          updatedTime: bigint
          firstName: varchar(255)
          lastName: varchar(255)

      medicaldb.backoffice_user_preferences:
        +column_types:
          _id: varchar(50)
          updatedTime: bigint

      medicaldb.patient_followups:
        +column_types:
          _id: varchar(50)
          createdTime: bigint
          dob: bigint
          lastFollowupAt: bigint
          updatedTime: bigint
          cPeptideDoneAt: bigint
          gadDoneAt: bigint
          fourthHba1cDate: bigint
          hba1cDate: bigint
          secondHba1cDate: bigint
          thirdHba1cDate: bigint
          deceasedDate: bigint
          followUpTime: bigint
          lastUpdatedTime: bigint

      medicaldb.patient_history:
        +column_types:
          _id: varchar(50)
          createdTime: bigint
          dob: bigint
          cPeptideDoneAt: bigint
          gadDoneAt: bigint
          updatedTime: bigint
          lastFollowupAt: bigint
          hba1cDate: bigint
          secondHba1cDate: bigint
          thirdHba1cDate: bigint
          fourthHba1cDate: bigint
          lastUpdatedTime: bigint
          deceasedDate: bigint
          followUpTime: bigint
          updateSequence: bigint
          contactNumber2: bigint   

      medicaldb.patient_latest_data:
        +column_types:
          _id: varchar(50)
          createdTime: bigint
          dob: bigint
          lastFollowupAt: bigint
          updatedTime: bigint
          cPeptideDoneAt: bigint
          gadDoneAt: bigint
          fourthHba1cDate: bigint
          hba1cDate: bigint
          secondHba1cDate: bigint
          thirdHba1cDate: bigint
          deceasedDate: bigint
          followUpTime: bigint
          lastUpdatedTime: bigint
          updateSequence: bigint
          contactNumber: bigint
          contactNumber2: bigint

      medicaldb.patients:
        +column_types:
          _id: varchar(50)
          dob: bigint
          createdTime: bigint
          updatedTime: bigint
          lastFollowupAt: bigint
          cPeptideDoneAt: bigint
          gadDoneAt: bigint
          fourthHba1cDate: bigint
          hba1cDate: bigint
          secondHba1cDate: bigint
          thirdHba1cDate: bigint
          deceasedDate: bigint
          followUpTime: bigint
          lastUpdatedTime: bigint
          updateSequence: bigint
          contactNumber: bigint
          contactNumber2: bigint

      medicaldb.roles:
        +column_types:
          _id: varchar(50)
          updatedTime: bigint

    # static data seeds
    lookups:
      +schema: platform

# Models configuration
models:
  dbt_project:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    marts:
      +materialized: table
      +schema: platform

      core:
        +tags: ["core"]

      patients:
        +tags: ["patients"]
        patient_versions:
          +materialized: table

      lookups:
        +tags: ["lookups"]

vars:
  migration_date: "{{ run_started_at }}"
